In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 

from sklearn.model_selection import train_test_split

In [2]:
url='https://archive.ics.uci.edu/ml/machine-learning-databases/glass/glass.data'
names=['RI','Na','Mg','Al','Si','K','Ca','Ba','Fe','target']
glass_dataset=pd.read_csv(url,header=None,names=names)

In [3]:
glass_dataset

          RI     Na    Mg    Al     Si     K    Ca    Ba    Fe  target
1    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.00       1
2    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.00       1
3    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.00       1
4    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.00       1
5    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.00       1
6    1.51596  12.79  3.61  1.62  72.97  0.64  8.07  0.00  0.26       1
7    1.51743  13.30  3.60  1.14  73.09  0.58  8.17  0.00  0.00       1
8    1.51756  13.15  3.61  1.05  73.24  0.57  8.24  0.00  0.00       1
9    1.51918  14.04  3.58  1.37  72.08  0.56  8.30  0.00  0.00       1
10   1.51755  13.00  3.60  1.36  72.99  0.57  8.40  0.00  0.11       1
11   1.51571  12.72  3.46  1.56  73.20  0.67  8.09  0.00  0.24       1
12   1.51763  12.80  3.66  1.27  73.01  0.60  8.56  0.00  0.00       1
13   1.51589  12.88  3.43  1.40  73.28  0.69  8.05  0.00  0.24       1
14   1.51748  12.86  3.56  1.27  73.21  0.54  8.38  0.00  0.17       1
15   1.51763  12.61  3.59  1.31  73.29  0.58  8.50  0.00  0.00       1
16   1.51761  12.81  3.54  1.23  73.24  0.58  8.39  0.00  0.00       1
17   1.51784  12.68  3.67  1.16  73.11  0.61  8.70  0.00  0.00       1
18   1.52196  14.36  3.85  0.89  71.36  0.15  9.15  0.00  0.00       1
19   1.51911  13.90  3.73  1.18  72.12  0.06  8.89  0.00  0.00       1
20   1.51735  13.02  3.54  1.69  72.73  0.54  8.44  0.00  0.07       1
21   1.51750  12.82  3.55  1.49  72.75  0.54  8.52  0.00  0.19       1
22   1.51966  14.77  3.75  0.29  72.02  0.03  9.00  0.00  0.00       1
23   1.51736  12.78  3.62  1.29  72.79  0.59  8.70  0.00  0.00       1
24   1.51751  12.81  3.57  1.35  73.02  0.62  8.59  0.00  0.00       1
25   1.51720  13.38  3.50  1.15  72.85  0.50  8.43  0.00  0.00       1
26   1.51764  12.98  3.54  1.21  73.00  0.65  8.53  0.00  0.00       1
27   1.51793  13.21  3.48  1.41  72.64  0.59  8.43  0.00  0.00       1
28   1.51721  12.87  3.48  1.33  73.04  0.56  8.43  0.00  0.00       1
29   1.51768  12.56  3.52  1.43  73.15  0.57  8.54  0.00  0.00       1
30   1.51784  13.08  3.49  1.28  72.86  0.60  8.49  0.00  0.00       1
..       ...    ...   ...   ...    ...   ...   ...   ...   ...     ...
185  1.51115  17.38  0.00  0.34  75.41  0.00  6.65  0.00  0.00       6
186  1.51131  13.69  3.20  1.81  72.81  1.76  5.43  1.19  0.00       7
187  1.51838  14.32  3.26  2.22  71.25  1.46  5.79  1.63  0.00       7
188  1.52315  13.44  3.34  1.23  72.38  0.60  8.83  0.00  0.00       7
189  1.52247  14.86  2.20  2.06  70.26  0.76  9.76  0.00  0.00       7
190  1.52365  15.79  1.83  1.31  70.43  0.31  8.61  1.68  0.00       7
191  1.51613  13.88  1.78  1.79  73.10  0.00  8.67  0.76  0.00       7
192  1.51602  14.85  0.00  2.38  73.28  0.00  8.76  0.64  0.09       7
193  1.51623  14.20  0.00  2.79  73.46  0.04  9.04  0.40  0.09       7
194  1.51719  14.75  0.00  2.00  73.02  0.00  8.53  1.59  0.08       7
195  1.51683  14.56  0.00  1.98  73.29  0.00  8.52  1.57  0.07       7
196  1.51545  14.14  0.00  2.68  73.39  0.08  9.07  0.61  0.05       7
197  1.51556  13.87  0.00  2.54  73.23  0.14  9.41  0.81  0.01       7
198  1.51727  14.70  0.00  2.34  73.28  0.00  8.95  0.66  0.00       7
199  1.51531  14.38  0.00  2.66  73.10  0.04  9.08  0.64  0.00       7
200  1.51609  15.01  0.00  2.51  73.05  0.05  8.83  0.53  0.00       7
201  1.51508  15.15  0.00  2.25  73.50  0.00  8.34  0.63  0.00       7
202  1.51653  11.95  0.00  1.19  75.18  2.70  8.93  0.00  0.00       7
203  1.51514  14.85  0.00  2.42  73.72  0.00  8.39  0.56  0.00       7
204  1.51658  14.80  0.00  1.99  73.11  0.00  8.28  1.71  0.00       7
205  1.51617  14.95  0.00  2.27  73.30  0.00  8.71  0.67  0.00       7
206  1.51732  14.95  0.00  1.80  72.99  0.00  8.61  1.55  0.00       7
207  1.51645  14.94  0.00  1.87  73.11  0.00  8.67  1.38  0.00       7
208  1.51831  14.39  0.00  1.82  72.86  1.41  6.47  2.88  0.00       7
209  1.51640  14.37  0.00  2.74  72.85  0.00  9.45  0.54  0.00       7
210  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.00       7
211  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.00       7
212  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.00       7
213  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.00       7
214  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.00       7

[214 rows x 10 columns]

In [4]:
features=glass_dataset.drop('target',axis=1)

In [5]:
features.head()

        RI     Na    Mg    Al     Si     K    Ca   Ba   Fe
1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0
2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0
3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0
4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0
5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0

In [6]:
target=glass_dataset.drop(['RI','Na','Mg','Al','Si','K','Ca','Ba','Fe'],axis=1)

In [7]:
target.head()

   target
1       1
2       1
3       1
4       1
5       1

In [8]:
features=(features-features.min())/(features.max()-features.min())

In [9]:
xtrain,xtest,ytrain,ytest=train_test_split(features,target,test_size=0.3)

In [10]:
correlation=glass_dataset.corr('pearson')

In [11]:
correlation['target'].sort_values()

Mg       -0.744993
Fe       -0.188278
RI       -0.164237
K        -0.010054
Ca        0.000952
Si        0.151565
Na        0.502898
Ba        0.575161
Al        0.598829
target    1.000000
Name: target, dtype: float64

In [51]:
f1='Mg'
f2='Al'

basex=np.array(xtrain[[f1,f2]])
basey=np.array(ytrain['target'])

testx=np.array(xtest[[f1,f2]])
testy=np.array(ytest['target'])

In [52]:
def euclidean_distance(train_point,test_point):
    distance=np.sum((train_point-test_point)**2)
    
    return np.sqrt(distance)

In [53]:
def calc_distance_from_all(all_points,given_point,predictions):
    all_distances=[]
    
    for i,each in enumerate(all_points):
        distance=euclidean_distance(each,given_point)
        all_distances.append((distance,int(predictions[i])))
        
    all_distances.sort(key=lambda tup: tup[0])
    
    return all_distances

In [54]:
def get_neighbours(distances,count):
    return distances[:count]

In [55]:
def predict(all_points,given_point,predictions):
    distances = calc_distance_from_all(all_points,given_point,predictions)
    neighbours=get_neighbours(distances,13)
    
    op=[row[-1] for row in neighbours]#op is output variable.
    prediction=max(set(op),key=op.count)
    
    return prediction

In [56]:
def accuracy(basex,basey,testx,testy):
    correct=0
    for i in range(len(testx)):
        p=predict(basex,testx[i],basey)
        
        if p == testy[i]:
            correct+=1
    return f"Accuracy:{correct*100/len(testy)}"

In [57]:
accuracy(basex,basey,testx,testy)

'Accuracy:60.0'